name: CI testapka
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push

jobs:
  Install-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run ESLint style check
        run: npm run lint
